--
-- File generated with SQLiteStudio v3.4.17 on sab ott 11 11:41:03 2025
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: interrogatori
CREATE TABLE IF NOT EXISTS interrogatori (
      id_sospettato INTEGER,
      trascrizione TEXT,
      FOREIGN KEY(id_sospettato) REFERENCES sospettati(id)
    );
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (1, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (2, 'Ero a casa tutto il giorno, non ho idea di cosa sia successo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (3, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (4, 'Non ho alcun ricordo di quell''evento.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (5, 'Ero al lavoro, non potevo essere coinvolto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (6, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (7, 'Ero con amici in un ristorante.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (8, 'Non so nulla dell''incidente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (9, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (10, 'Non sapevo nemmeno che stesse succedendo qualcosa.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (11, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (12, 'Non ho visto nulla di sospetto, assolutamente nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (13, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (14, 'Ero fuori città per un viaggio.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (15, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (16, 'Ero con la famiglia per tutta la sera.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (17, 'Stavo dormendo a quell''ora.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (18, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (19, 'Non ho idea della situazione.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (20, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (21, 'Non ho sentito nulla, stavo guardando un film.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (22, 'Ero bloccato nel traffico, non ho visto nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (23, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (24, 'Non ne ho idea di quell''evento.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (25, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (26, 'Non ero nemmeno in zona, mi dispiace.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (27, 'Non ho alcun collegamento con l''incidente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (28, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (29, 'Non ero affatto vicino al luogo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (30, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (31, 'Non facevo parte di niente di tutto questo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (32, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (33, 'Non ho avuto parte in nulla di ciò che è successo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (34, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (35, 'Non ero coinvolto in nulla di sospetto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (36, 'Ero fuori con amici, non ne ho nemmeno sentito parlare.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (37, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (38, 'Non sono sicuro di cosa sia successo, ma non ero vicino.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (39, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (40, 'Non ho idea della situazione.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (41, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (42, 'Non ero da nessuna parte vicino a quella zona.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (43, 'Non so nulla al riguardo, mi dispiace.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (44, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (45, 'Ero impegnato al lavoro, non ho tempo per altro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (46, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (47, 'Non c''entravo nulla, sono innocente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (48, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (49, 'Non sapevo nemmeno che stesse accadendo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (50, 'Ero con un amico per tutto il tempo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (51, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (52, 'Non ero lì, e non so nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (53, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (54, 'Non sono coinvolto in alcun modo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (55, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (56, 'Non ho sentito nulla, ero occupato.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (57, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (58, 'Non ho visto nulla di strano.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (59, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (60, 'Non so nulla di quello che è successo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (61, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (62, 'Ero fuori città quel giorno, non ne ho idea.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (63, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (64, 'Non ho visto nulla di insolito accadere.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (65, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (66, 'Non sono stato coinvolto, ho un alibi.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (67, 'Non ne ho fatto parte, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (68, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (69, 'Non sapevo nemmeno che stesse succedendo qualcosa.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (70, 'Non c''entro niente con questo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (71, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (72, 'Ero al negozio, non c''entro nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (73, 'Non ero in zona, ho delle prove.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (74, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (75, 'Non so nulla, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (76, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (77, 'Non ero da nessuna parte lì vicino.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (78, 'Ero a casa, badando ai miei affari.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (79, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (80, 'Non facevo parte di nulla di tutto questo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (81, 'Non ho sentito nulla quella notte.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (82, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (83, 'Non lo so, non ero lì.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (84, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (85, 'Non avevo idea di cosa stesse succedendo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (86, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (87, 'Non ho visto nulla di strano, assolutamente nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (88, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (89, 'Non so nulla al riguardo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (90, 'Ero con i miei amici, nessun coinvolgimento.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (91, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (92, 'Ero a casa, non è successo nulla intorno a me.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (93, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (94, 'Non so nemmeno cosa sia successo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (95, 'Ero altrove, non posso essere io.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (96, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (97, 'Non ero lì vicino, lo prometto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (98, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (99, 'Non so nemmeno del crimine.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (100, 'Non ero vicino al posto, non ne ho idea.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (101, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (102, 'Non ero lì, posso provarlo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (103, 'Non ho nulla da dire al riguardo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (104, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (105, 'Non ho sentito o visto nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (106, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (107, 'Sono innocente, non ho fatto nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (108, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (109, 'Non ero in citta'' durante l''incidente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (110, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (111, 'Non so chi ci sia dietro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (112, 'Non ero da nessuna parte lì vicino, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (113, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (114, 'Non sapevo nemmeno del crimine.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (115, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (116, 'Ero impegnato con il lavoro, non ho notato nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (117, 'Non ho visto nulla, ero fuori città.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (118, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (119, 'Non sono affatto coinvolto, lo prometto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (120, 'Non so nulla del furto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (121, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (122, 'Non ero lì per niente, non avrei potuto fare nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (123, 'Non ho avuto parte in questo, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (124, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (125, 'Non so nemmeno di chi state parlando.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (126, 'Non sono stato coinvolto, non ne ho nemmeno sentito parlare.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (127, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (128, 'Non ero vicino a quel posto, nessun collegamento.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (129, 'Non sono stato coinvolto, fidati di me.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (130, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (131, 'Ero con un amico tutta la notte.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (132, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (133, 'Non ero in città quella sera, impossibile.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (134, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (135, 'Non sapevo nemmeno dell''incidente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (136, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (137, 'Non ero affatto vicino alla zona.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (138, 'Ero in palestra, non posso essere io.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (139, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (140, 'Non ho visto nulla quella notte.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (141, 'Non so nulla, mi dispiace.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (142, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (143, 'Non ho sentito o visto nulla, ero a letto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (144, 'Non ero lì, sono innocente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (145, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (146, 'Non ero nemmeno vicino alla scena del crimine.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (147, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (148, 'Ero con la famiglia, non ho visto nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (149, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (150, 'Non sono stato coinvolto, lo giuro sulla mia vita.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (151, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (152, 'Non so nulla, non ero lì.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (153, 'Non ho alcun collegamento con l''incidente.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (154, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (155, 'Non facevo parte di questo, ho un alibi.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (156, 'Non so nulla del crimine.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (157, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (158, 'Non ho visto nulla, ero occupato al lavoro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (159, 'Non so nulla del furto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (160, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (161, 'Non ero vicino alla scena del crimine, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (162, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (163, 'Non ne so nemmeno nulla, mi dispiace.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (164, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (165, 'Non ero lì, lo prometto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (166, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (167, 'Non sono stata coinvolta in alcun modo, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (168, 'Non ho visto nulla di sospetto.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (169, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (170, 'Non so di cosa stai parlando.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (171, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (172, 'Non ho nemmeno saputo del crimine.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (173, 'Non ero vicino alla scena.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (174, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (175, 'Non ho alcun coinvolgimento in questo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (176, 'Non ho sentito nulla, stavo dormendo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (177, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (178, 'Non sono stata coinvolta per niente, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (179, 'Stavo lavorando quel giorno, non posso essere io.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (180, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (181, 'Non ero vicino al posto, non ho visto nulla.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (182, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (183, 'Non avevo intenzione di rubarlo, ma sono stato io.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (184, 'Non ho idea di cosa sia successo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (185, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (186, 'Ero a casa quel giorno, non lo sapevo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (187, 'Non ne ho fatto parte, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (188, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (189, 'Non so nulla al riguardo, non ero lì.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (190, 'Non sono stata coinvolta in niente di tutto questo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (191, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (192, 'Non ho visto nulla, lo giuro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (193, 'Non ero in giro, ero impegnato al lavoro.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (194, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (195, 'Non sapevo nemmeno del crimine.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (196, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (197, 'Non ho idea di chi abbia fatto questo.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (198, NULL);
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (199, 'Non sono stato coinvolto, ero al parco.');
INSERT INTO interrogatori (id_sospettato, trascrizione) VALUES (200, 'Non ho visto nulla di sospetto, mi dispiace.');
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
