--
-- File generated with SQLiteStudio v3.4.17 on sab ott 11 11:25:31 2025
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: sospettati
CREATE TABLE IF NOT EXISTS sospettati (
      id INTEGER PRIMARY KEY,
      nome TEXT,
      abbigliamento TEXT,
      cicatrice TEXT
    );
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (1, 'Michael Johnson', 'nessuno', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (2, 'Tony DeMarco', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (3, 'Frankie Lombardi', 'trench coat', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (4, 'Carlos Garcia', 'giacca', 'braccio destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (5, 'Marko Shvets', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (6, 'Amanda Taylor', 'camicetta', 'gamba destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (7, 'Richard Brown', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (8, 'Heather Williams', 'vestito', 'mano sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (9, 'Joshua Smith', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (10, 'Claire Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (11, 'Evan Davis', 'maglione', 'spalla destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (12, 'Nina Patel', 'gonna', 'braccio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (13, 'Sam Johnson', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (14, 'Maya Nguyen', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (15, 'Daniel King', 'blazer', 'coscia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (16, 'Laura Wright', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (17, 'Chris Scott', 'felpa con cappuccio', 'polso destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (18, 'Sophie Harris', 'maglione', 'piede sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (19, 'Tommy Walker', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (20, 'Ava Lewis', 'vestito', 'ginocchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (21, 'Victor Carter', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (22, 'Mason Clark', 'giacca', 'orecchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (23, 'Zoe Mitchell', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (24, 'Oliver Hall', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (25, 'Ellie Anderson', 't-shirt', 'piede destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (26, 'Andrew Moore', 'blazer', 'guancia destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (27, 'Penny Turner', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (28, 'Benjamin Lopez', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (29, 'Sophia Martin', 'vestito', 'spalla sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (30, 'Matthew Collins', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (31, 'Emily Adams', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (32, 'Lucas Stewart', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (33, 'Chloe Baker', 'gonna', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (34, 'Liam Mitchell', 't-shirt', 'polso sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (35, 'Charlotte White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (36, 'James Young', 'cardigan', 'gamba destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (37, 'Ella King', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (38, 'Lucas Scott', 'giacca', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (39, 'Aiden Gonzalez', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (40, 'Amelia Green', 'vestito', 'polso sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (41, 'William Johnson', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (42, 'Mila Roberts', 'maglione', 'mano destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (43, 'Jackson Mitchell', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (44, 'Grace Moore', 't-shirt', 'ginocchio destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (45, 'John Lee', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (46, 'Lily Jackson', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (47, 'Daniel Taylor', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (48, 'Sophie Harris', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (49, 'Benjamin White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (50, 'Dylan Walker', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (51, 'Gabriella Cooper', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (52, 'Sebastian Smith', 'giacca', 'mano sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (53, 'Sophie Jones', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (54, 'Ethan Brown', 't-shirt', 'spalla destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (55, 'Elijah Johnson', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (56, 'Charlotte Robinson', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (57, 'Maddison Lewis', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (58, 'Alexander Campbell', 'vestito', 'ginocchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (59, 'Mia Cooper', 'gonna', 'braccio destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (60, 'Ethan Carter', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (61, 'Sophia Harris', 'giacca', 'coscia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (62, 'Grace Scott', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (63, 'Benjamin Miller', 'abito', 'guancia destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (64, 'Madeline Taylor', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (65, 'Olivia Young', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (66, 'Jack Mitchell', 'giacca', 'polso destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (67, 'Isabella Wilson', 'vestito', 'braccio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (68, 'Aiden Turner', 'camicetta', 'gamba destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (69, 'Aria Morgan', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (70, 'Ryan Nelson', 'felpa con cappuccio', 'ginocchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (71, 'Lily White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (72, 'James Carter', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (73, 'Chloe Anderson', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (74, 'Ava Moore', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (75, 'Michael Scott', 'vestito', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (76, 'Emma Hall', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (77, 'David Davis', 'maglione', 'mano destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (78, 'Lucas White', 't-shirt', 'polso sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (79, 'Lily Smith', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (80, 'Mason Turner', 'blazer', 'ginocchio destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (81, 'Matthew Jackson', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (82, 'Sophie Robinson', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (83, 'Isaac Martin', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (84, 'Maya Green', 'maglione', 'mano sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (85, 'James Lee', 't-shirt', 'guancia destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (86, 'Jack Robinson', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (87, 'Olivia Walker', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (88, 'Ella Cooper', 'maglione', 'polso destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (89, 'Liam Davis', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (90, 'Oliver Harris', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (91, 'Charlotte King', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (92, 'David Young', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (93, 'Sebastian Lewis', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (94, 'Emma Carter', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (95, 'Maxwell Taylor', 'giacca', 'orecchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (96, 'Benjamin White', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (97, 'Chloe Lee', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (98, 'Amelia Walker', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (99, 'Dylan Lewis', 'camicetta', 'gamba destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (100, 'Ryan Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (101, 'Sophie Turner', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (102, 'Lucas Scott', 'maglione', 'polso sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (103, 'Maddison Carter', 'giacca', 'spalla destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (104, 'Jackson Brown', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (105, 'Victoria Cooper', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (106, 'Evan Lewis', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (107, 'David Wilson', 'camicetta', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (108, 'Sophia Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (109, 'Charlotte Harris', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (110, 'Oliver Carter', 'maglione', 'mano destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (111, 'Emily Taylor', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (112, 'John White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (113, 'Amelia Brown', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (114, 'Lucas Moore', 'vestito', 'ginocchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (115, 'David Cooper', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (116, 'Oliver Harris', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (117, 'Maya Walker', 'cardigan', 'piede destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (118, 'Sophia Green', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (119, 'James Taylor', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (120, 'Mason Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (121, 'Olivia King', 't-shirt', 'coscia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (122, 'Charlotte White', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (123, 'Mia Davis', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (124, 'Maddison Turner', 'giacca', 'polso destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (125, 'Isabella Martin', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (126, 'Benjamin White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (127, 'David Lewis', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (128, 'Sophie Green', 'cardigan', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (129, 'Liam Martin', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (130, 'Ella Turner', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (131, 'Chloe King', 't-shirt', 'piede destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (132, 'Sebastian Walker', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (133, 'Olivia White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (134, 'Mason Turner', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (135, 'Victor Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (136, 'Benjamin Harris', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (137, 'Isabella Davis', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (138, 'Mia Green', 'cardigan', 'braccio destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (139, 'Liam Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (140, 'Emily White', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (141, 'Olivia Turner', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (142, 'David King', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (143, 'Matthew Scott', 'maglione', 'spalla destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (144, 'Isabella White', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (145, 'Aiden Harris', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (146, 'Benjamin Green', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (147, 'Sophia Turner', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (148, 'Oliver Harris', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (149, 'Ethan King', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (150, 'Chloe Brown', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (151, 'Zoe Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (152, 'Lucas Carter', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (153, 'Sophia Martin', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (154, 'Mason Lee', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (155, 'Olivia White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (156, 'Benjamin Scott', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (157, 'Chloe Davis', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (158, 'Liam Young', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (159, 'David Green', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (160, 'Ethan Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (161, 'Olivia King', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (162, 'Sophie Harris', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (163, 'Lily Brown', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (164, 'Benjamin Walker', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (165, 'Matthew Davis', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (166, 'Victor Young', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (167, 'Isabella White', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (168, 'David Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (169, 'Chloe Walker', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (170, 'Olivia Green', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (171, 'Zoe Harris', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (172, 'Liam White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (173, 'Benjamin Carter', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (174, 'Sophie Turner', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (175, 'Lucas Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (176, 'Mason White', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (177, 'David Harris', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (178, 'Olivia King', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (179, 'Liam Turner', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (180, 'Sophie Davis', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (181, 'Victor Green', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (182, 'Sophia Taylor', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (183, 'Vincent Malone', 'trench coat', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (184, 'Benjamin Young', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (185, 'Olivia White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (186, 'Mason Davis', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (187, 'David King', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (188, 'Chloe Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (189, 'Victor Harris', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (190, 'Sophie King', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (191, 'Olivia Green', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (192, 'Isabella Walker', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (193, 'Benjamin White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (194, 'Ethan Turner', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (195, 'David Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (196, 'Chloe Walker', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (197, 'Liam Davis', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (198, 'Olivia White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (199, 'Victor Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (200, 'Sophie Taylor', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (201, 'Mason Walker', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (202, 'David White', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (203, 'Olivia Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (204, 'Zoe King', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (205, 'Liam Young', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (206, 'Sophie Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (207, 'Victor White', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (208, 'Olivia Davis', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (209, 'Lucas Brown', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (210, 'David Harris', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (211, 'Sophie Turner', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (212, 'Isabella King', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (213, 'Benjamin Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (214, 'Ethan Davis', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (215, 'Victor Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (216, 'Lily White', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (217, 'Mason King', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (218, 'David Taylor', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (219, 'Olivia Walker', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (220, 'Lucas Davis', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (221, 'Zoe Brown', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (222, 'Sophia Taylor', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (223, 'Victor Walker', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (224, 'Mason Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (225, 'Ethan Brown', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (226, 'David Harris', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (227, 'Olivia Walker', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (228, 'Zoe Taylor', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (229, 'Lucas Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (230, 'Victor King', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (231, 'Isabella Harris', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (232, 'Benjamin Green', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (233, 'Olivia Brown', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (234, 'David Walker', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (235, 'Victor Davis', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (236, 'Sophie King', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (237, 'Christopher Black', 'trench coat', 'guancia destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (238, 'Mason Taylor', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (239, 'Olivia Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (240, 'Victor Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (241, 'Liam White', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (242, 'Ethan King', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (243, 'Sophia Brown', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (244, 'Olivia Taylor', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (245, 'David Walker', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (246, 'Benjamin Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (247, 'Victor White', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (248, 'Zoe Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (249, 'Lucas Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (250, 'Mason King', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (251, 'David Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (252, 'Olivia Green', 'blazer', 'gamba sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (253, 'Victor Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (254, 'Mason Walker', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (255, 'Zoe Harris', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (256, 'Isabella Brown', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (257, 'Ethan Green', 't-shirt', 'guancia sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (258, 'Sophie White', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (259, 'Olivia Brown', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (260, 'David King', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (261, 'Zoe Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (262, 'Mason White', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (263, 'Benjamin Walker', 'giacca', 'mano destra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (264, 'Olivia Brown', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (265, 'Victor Green', 'maglione', 'ginocchio sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (266, 'Sophie Harris', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (267, 'Isabella Brown', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (268, 'Mason King', 'camicetta', 'piede destro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (269, 'Zoe White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (270, 'David Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (271, 'Lucas Green', 't-shirt', 'polso sinistro');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (272, 'Victor Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (273, 'Benjamin White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (274, 'Isabella Harris', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (275, 'Sophie Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (276, 'Olivia Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (277, 'David White', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (278, 'Victor Taylor', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (279, 'Liam Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (280, 'Mason Brown', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (281, 'Sophia White', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (282, 'Zoe King', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (283, 'David Harris', 'giacca', 'spalla sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (284, 'Victor White', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (285, 'Olivia Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (286, 'Lucas King', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (287, 'Mason White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (288, 'Sophia Taylor', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (289, 'Isabella Harris', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (290, 'Ethan Green', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (291, 'David Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (292, 'Olivia King', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (293, 'Mason Green', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (294, 'Victor Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (295, 'Sophia White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (296, 'Isabella King', 'giacca', 'mano sinistra');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (297, 'Zoe Brown', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (298, 'Mason Taylor', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (299, 'David Harris', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (300, 'Olivia Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (301, 'Zoe White', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (302, 'Victor Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (303, 'Mason Harris', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (304, 'Lucas White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (305, 'Benjamin King', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (306, 'Isabella Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (307, 'David Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (308, 'Olivia Walker', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (309, 'Sophia White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (310, 'Zoe Taylor', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (311, 'Mason Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (312, 'Victor Harris', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (313, 'Sophia Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (314, 'Benjamin Taylor', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (315, 'Zoe Walker', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (316, 'David King', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (317, 'Isabella White', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (318, 'Mason Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (319, 'Victor Green', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (320, 'Sophia King', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (321, 'Lucas White', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (322, 'Benjamin Green', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (323, 'Olivia Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (324, 'Victor King', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (325, 'Zoe Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (326, 'Mason Harris', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (327, 'David White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (328, 'Olivia King', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (329, 'Sophie Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (330, 'Isabella Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (331, 'Mason Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (332, 'Lucas White', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (333, 'David Harris', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (334, 'Victor Green', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (335, 'Sophie White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (336, 'Benjamin Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (337, 'Olivia Taylor', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (338, 'Mason Walker', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (339, 'Victor Harris', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (340, 'Zoe Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (341, 'Sophie Taylor', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (342, 'David White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (343, 'Lucas Harris', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (344, 'Olivia Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (345, 'Victor Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (346, 'Isabella Walker', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (347, 'Benjamin White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (348, 'Mason King', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (349, 'Sophie Brown', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (350, 'David King', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (351, 'Lucas White', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (352, 'Isabella Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (353, 'Zoe Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (354, 'Sophie White', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (355, 'Victor Taylor', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (356, 'Benjamin Walker', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (357, 'Olivia Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (358, 'Mason White', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (359, 'David Harris', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (360, 'Victor Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (361, 'Zoe King', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (362, 'Sophia White', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (363, 'Olivia Brown', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (364, 'Isabella Green', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (365, 'David Brown', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (366, 'Mason White', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (367, 'Victor Green', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (368, 'Sophie Harris', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (369, 'Benjamin Walker', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (370, 'Olivia Brown', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (371, 'Victor Green', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (372, 'Sophia White', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (373, 'Isabella Taylor', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (374, 'Mason White', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (375, 'David Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (376, 'Sophie Green', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (377, 'Lucas White', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (378, 'Olivia Harris', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (379, 'Victor White', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (380, 'Sophie Walker', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (381, 'Benjamin Brown', 'camicetta', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (382, 'David White', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (383, 'Lucas Green', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (384, 'Sophie Brown', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (385, 'Olivia King', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (386, 'Victor Green', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (387, 'Zoe Taylor', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (388, 'Isabella Walker', 't-shirt', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (389, 'Benjamin Brown', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (390, 'Mason Green', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (391, 'David Walker', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (392, 'Olivia Brown', 'giacca', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (393, 'Victor White', 'smoking', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (394, 'Sophia Green', 'vestito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (395, 'Isabella Brown', 'abito', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (396, 'David King', 'blazer', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (397, 'Mason White', 'felpa con cappuccio', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (398, 'Victor Taylor', 'cardigan', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (399, 'Olivia Harris', 'maglione', 'nessuna');
INSERT INTO sospettati (id, nome, abbigliamento, cicatrice) VALUES (400, 'Benjamin Walker', 'giacca', 'nessuna');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
